### ISSUE TITLE
Kafka_2.11 Scala

### ISSUE THREAD

**Issue by MazizEsa** [hubrick/vertx-kafka-service#13]
Dear all,
I would like to contribute so that we can have another version of this plugin using kafka_2.11 client. This is because if you use for example mysql-postgres vertx plugin together with this you will be having transitive dependency conflict (mysql-postgres vertx is using 2.11 and this one using 2.10).

Please advise on how to have this with 2 version. I can create a PR but I am not sure how you going to version it as release to maven repo.

Regards.

**Comment by eemmiirr** [comment]
Hi,

could you please create a PR which will basically change the maven build so it uses different classifiers for the different versions of scala so we can support all of the versions out there. Something like this: http://stackoverflow.com/questions/12320322/build-multiple-artifacts-with-different-classifiers-at-once.

Thanks you for the contribution

**Comment by MazizEsa** [comment]
Got it. Will come up with a PR soon.

**Comment by MazizEsa** [comment]
@eemmiirr shouldn't the usage of profiles would be more appropriate here? Not advisable to produce multiple artifacts on 1 pom.

**Comment by eemmiirr** [comment]
@MazizEsa tried to implement it but then came to the conclusion that it doesn't make much sense so can't you just override it since it's anyway a transitive dependency. Will this work out?
